baseURL = 'https://storage-memo.steinslab.io'
languageCode = 'zh-cn'
title = '分布式存储漫游指南'
theme = 'hextra'

# Google Analytics 配置（主题已内置 _partials/google-analytics.html，会在生产环境注入 gtag.js）
[services]
  [services.googleAnalytics]
    ID = 'G-1CPZP87MFH'

# Redirect root to docs
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[languages]
  [languages.zh-cn]
    languageName = "简体中文"
    weight = 1
    title = "分布式存储漫游指南"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1

[menu]
  [[menu.main]]
    name = "关于"
    pageRef = "/about"
    weight = 20
  [[menu.main]]
    name = "作者 Blog"
    url = "https://steinslab.io/"
    weight = 25
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/sptuan/dist-storage-mono"
    weight = 30
    [menu.main.params]
      icon = "github"

[params]

  # Mermaid diagrams
  [params.mermaid]
    enable = true

  [params.navbar]
    displayTitle = true
    displayLogo = false
    # 导航栏宽度与页面保持一致
    width = "wide"

  [params.page]
    # (Optional, default true) Display navigation breadcrumb
    breadcrumb = true
    # 页面宽度设置：full (100%), wide (90rem), normal (1280px)
    width = "wide"

  [params.footer]
    displayCopyright = true
    displayPoweredBy = true
    # 页脚宽度与页面保持一致
    width = "wide"

  displayUpdatedDate = true
  dateFormat = "January 2, 2006"

  # Search
  # flexsearch is enabled by default
  [params.search]
    enable = true
    type = "flexsearch"

  [params.editPage]
    enable = false

  [params.theme]
    default = "system"

  # Social links
  [[params.navbar.socialLinks]]
    name = "github"
    url = "https://github.com/sptuan/dist-storage-mono"
    icon = "github"
